/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMyDsl2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDsl2IdeModule extends AbstractMyDsl2IdeModule {
}
