/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl.ui.AbstractMyDsl2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDsl2UiModule extends AbstractMyDsl2UiModule {
  public MyDsl2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
