/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl2.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl2.MainModel;
import org.xtext.example.mydsl.myDsl2.MyDsl2Package;
import org.xtext.example.mydsl.myDsl2.Season;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Main Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl2.impl.MainModelImpl#getSeasons <em>Seasons</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MainModelImpl extends MinimalEObjectImpl.Container implements MainModel
{
  /**
   * The cached value of the '{@link #getSeasons() <em>Seasons</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeasons()
   * @generated
   * @ordered
   */
  protected EList<Season> seasons;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MainModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDsl2Package.Literals.MAIN_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Season> getSeasons()
  {
    if (seasons == null)
    {
      seasons = new EObjectContainmentEList<Season>(Season.class, this, MyDsl2Package.MAIN_MODEL__SEASONS);
    }
    return seasons;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDsl2Package.MAIN_MODEL__SEASONS:
        return ((InternalEList<?>)getSeasons()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDsl2Package.MAIN_MODEL__SEASONS:
        return getSeasons();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDsl2Package.MAIN_MODEL__SEASONS:
        getSeasons().clear();
        getSeasons().addAll((Collection<? extends Season>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDsl2Package.MAIN_MODEL__SEASONS:
        getSeasons().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDsl2Package.MAIN_MODEL__SEASONS:
        return seasons != null && !seasons.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MainModelImpl
