/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl2;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl2.MainModel#getSeasons <em>Seasons</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl2.MyDsl2Package#getMainModel()
 * @model
 * @generated
 */
public interface MainModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Seasons</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl2.Season}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Seasons</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seasons</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl2.MyDsl2Package#getMainModel_Seasons()
   * @model containment="true"
   * @generated
   */
  EList<Season> getSeasons();

} // MainModel
