/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl2;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl2.MyDsl2Factory
 * @model kind="package"
 * @generated
 */
public interface MyDsl2Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl2";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl2";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl2";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDsl2Package eINSTANCE = org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl2.impl.MainModelImpl <em>Main Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl2.impl.MainModelImpl
   * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getMainModel()
   * @generated
   */
  int MAIN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Seasons</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL__SEASONS = 0;

  /**
   * The number of structural features of the '<em>Main Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl2.impl.SeasonImpl <em>Season</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl2.impl.SeasonImpl
   * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getSeason()
   * @generated
   */
  int SEASON = 1;

  /**
   * The feature id for the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEASON__ALT = 0;

  /**
   * The number of structural features of the '<em>Season</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEASON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl2.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl2.impl.ListImpl
   * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getList()
   * @generated
   */
  int LIST = 2;

  /**
   * The feature id for the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__ALT = 0;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl2.MainModel <em>Main Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Model</em>'.
   * @see org.xtext.example.mydsl.myDsl2.MainModel
   * @generated
   */
  EClass getMainModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl2.MainModel#getSeasons <em>Seasons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Seasons</em>'.
   * @see org.xtext.example.mydsl.myDsl2.MainModel#getSeasons()
   * @see #getMainModel()
   * @generated
   */
  EReference getMainModel_Seasons();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl2.Season <em>Season</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Season</em>'.
   * @see org.xtext.example.mydsl.myDsl2.Season
   * @generated
   */
  EClass getSeason();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl2.Season#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alt</em>'.
   * @see org.xtext.example.mydsl.myDsl2.Season#getAlt()
   * @see #getSeason()
   * @generated
   */
  EReference getSeason_Alt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl2.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see org.xtext.example.mydsl.myDsl2.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl2.List#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alt</em>'.
   * @see org.xtext.example.mydsl.myDsl2.List#getAlt()
   * @see #getList()
   * @generated
   */
  EAttribute getList_Alt();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDsl2Factory getMyDsl2Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl2.impl.MainModelImpl <em>Main Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl2.impl.MainModelImpl
     * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getMainModel()
     * @generated
     */
    EClass MAIN_MODEL = eINSTANCE.getMainModel();

    /**
     * The meta object literal for the '<em><b>Seasons</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_MODEL__SEASONS = eINSTANCE.getMainModel_Seasons();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl2.impl.SeasonImpl <em>Season</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl2.impl.SeasonImpl
     * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getSeason()
     * @generated
     */
    EClass SEASON = eINSTANCE.getSeason();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEASON__ALT = eINSTANCE.getSeason_Alt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl2.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl2.impl.ListImpl
     * @see org.xtext.example.mydsl.myDsl2.impl.MyDsl2PackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIST__ALT = eINSTANCE.getList_Alt();

  }

} //MyDsl2Package
