/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Season</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl2.Season#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl2.MyDsl2Package#getSeason()
 * @model
 * @generated
 */
public interface Season extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' containment reference.
   * @see #setAlt(List)
   * @see org.xtext.example.mydsl.myDsl2.MyDsl2Package#getSeason_Alt()
   * @model containment="true"
   * @generated
   */
  List getAlt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl2.Season#getAlt <em>Alt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' containment reference.
   * @see #getAlt()
   * @generated
   */
  void setAlt(List value);

} // Season
